export const ListProdutos = [{
    id: 1,
    name: "Veloz Vortex",
    marca: "Vortex",
    tipo:"Corrida",
    image: "../../public/tenis.svg",
    price: "200,00",
    priceDiscount: "139,99",
    type: 'Tênis',
    stars: 0.9,
    descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    avaliacoes: 100,
    ref: 38416711,
    tamanhos: ["39","40","41","42","43"],
    cores: ["#6FEEFF","#FF6969","#5E5E5E","#6D70B7"],
},
{
    id: 2,
    name: "SprintStar",
    marca:"Adidas",
    tipo:"Casual",
    image: "../../public/tenis.svg",
    price: "200,00",
    priceDiscount: "139,99",
    type: 'Tênis',
    stars: 4.5,
    descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    avaliacoes:100,
    ref: 38416712,
    tamanhos: ["39","40","41","42","43"],
    cores: ["#6FEEFF","#FF6969","#5E5E5E","#6D70B7"],
},
{
    id: 3,
    name: "Lunar Glide",
    marca:"Nike",
    tipo:"Casual",
    image: "../../public/tenis.svg",
    price: "200,00",
    priceDiscount: "139,99",
    type: 'Tênis',
    stars: 4,
    descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    avaliacoes: 100,
    ref: 38416713,
    tamanhos: ["39","40","41","42","43"],
    cores: ["#6FEEFF","#FF6969","#5E5E5E","#6D70B7"],
},
{
    id: 4,
    name: "AeroStride",
    marca:"Sporio",
    tipo:"Casual",
    image: "../../public/tenis.svg",
    price: "200,00",
    priceDiscount: "139,99",
    type: 'Tênis',
    stars: 1.9,
    descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    avaliacoes:100,
    ref: 38416714,
    tamanhos: ["39","40","41","42","43"],
    cores: ["#6FEEFF","#FF6969","#5E5E5E","#6D70B7"],
},
{
    id: 5,
    name: "Nimbus Flex",
    marca:"Asics",
    tipo:"Casual",
    image: "../../public/tenis.svg",
    price: "200,00",
    priceDiscount: "139,99",
    type: 'Tênis',
    stars: 2.5,
    descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    avaliacoes:100,
    ref: 38416715,
    tamanhos: ["39","40","41","42","43"],
    cores: ["#6FEEFF","#FF6969","#5E5E5E","#6D70B7"],
},
{
    id: 6,
    name: "Quantum Dash",
    marca:"Asics",
    tipo:"Casual",
    image: "../../public/tenis.svg",
    price: "200,00",
    priceDiscount: "139,99",
    type: 'Tênis',
    stars: 4.8,
    descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    avaliacoes: 100,
    ref: 38416716,
    tamanhos: ["39","40","41","42","43"],
    cores: ["#6FEEFF","#FF6969","#5E5E5E","#6D70B7"],
},
{
    id: 7,
    name: "Eclipse Runner",
    marca:"On Running",
    tipo:"Corrida",
    image: "../../public/tenis.svg",
    price: "200,00",
    priceDiscount: "139,99",
    type: 'Tênis',
    stars: 3.5,
    descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    avaliacoes: 100,
    ref: 38416717,
    tamanhos: ["39","40","41","42","43"],
    cores: ["#6FEEFF","#FF6969","#5E5E5E","#6D70B7"],
},
{
    id: 8,
    name: "Zenith Boost",
    marca:"Diadora",
    tipo:"Corrida",
    image: "../../public/tenis.svg",
    price: "200,00",
    priceDiscount: "139,99",
    type: 'Tênis',
    stars: 5, 
    descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    avaliacoes: 100,
    ref: 38416718,
    tamanhos: ["39","40","41","42","43"],
    cores: ["#6FEEFF","#FF6969","#5E5E5E","#6D70B7"],
},

]